---
#- name: copy mysql-server.cnf DB-Slaver
#  copy:
#    src:  Slaver-mysql-server.cnf
#    dest: /etc/my.cnf.d/mysql-server.cnf
#    owner: root
#    group: root
#    mode: 0644
#  when: ansible_facts.hostname == "cen102"
#
#- name: Copy file from local to centos102
#  copy:
#    src:  "master/{{ item }}"
#    dest: "/var/lib/mysql/master/"
#    owner: mysql
#    group: mysql
#    mode: 0640
#  with_items:
#    - ca.pem
#    - client-key.pem
#    - client-cert.pem

#- name: debug slaver
#  debug:
#    var: dbmaster
  #    var: find_output.Position
  #    var: find_output.File

#- name: Get master
#  mysql_replication:
#    login_user: replica
#    login_password: reppassword
#    login_host: 192.168.56.101
#    master_ssl: yes
#    login_unix_socket: /var/lib/mysql/mysql.sock
#    ca_cert: /var/lib/mysql/master/ca.pem
#    client_cert: /var/lib/mysql/master/client_cert.pem
#    client_key: /var/lib/mysql/master/client_key.pem
#    mode: getmaster
#  register: find_output
#- name: debug master
#  debug:
#    var: find_output

- name: Get master on slave
  mysql_replication:
    login_user: root
    login_password: password
    login_unix_socket: /var/lib/mysql/mysql.sock
    mode: getmaster
  register: master
  delegate_to: c81

- name: debug master
  debug:
    var: master

#- name: Configure replication on the slave.
#  mysql_replication:
#    mode: changemaster
#    master_host: "{{ mysql_replication_master }}"
#    master_user: "{{ mysql_replication_user.name }}"
#    master_password: "{{ mysql_replication_user.password }}"
#    master_log_file: "{{ master.File }}"
#    master_log_pos: "{{ master.Position }}"
