---
#
- hosts: virtualbox
  remote_user: ansible
  become: yes
  become_method: sudo
  tasks:
    - name: Install mariadb
      dnf:
        name: mariadb-server
        state: latest
    - name: Restart servie nginx
      systemd:
        state: restarted
        daemon_reload: yes
        name: mariadb
